<script setup lang="ts">
import { onMounted, ref } from "vue";
import { apiRequest } from "@/api/client";
import SkillUpload from "@/components/SkillUpload.vue";

type Skill = { id: string; name: string; version: string; type: string; status: string; description?: string; validation_warnings?: string[] };
type McpTool = { name: string; description?: string };
type Mcp = { id: string; name: string; transport: string; status: string; last_error?: string; tools?: McpTool[] };
type Invocation = { id: string; skill_id: string; owner_user_id: string; session_id: string; status: string; created_at?: string };
const skills = ref<Skill[]>([]); const mcps = ref<Mcp[]>([]); const invocations = ref<Invocation[]>([]);
const active = ref<"skills" | "mcp" | "invocations">("skills"); const error = ref(""); const busy = ref("");
const managerIds = ref<Record<string, string>>({});
const mcpManagerIds = ref<Record<string, string>>({});
const mcpForm = ref({ name: "", command: "", args: "" });
async function load() { try { const [s, m, i] = await Promise.all([apiRequest<{items: Skill[]}>("/api/business/skills"), apiRequest<{items: Mcp[]}>("/api/business/mcp-servers"), apiRequest<{items: Invocation[]}>("/api/business/skill-invocations")]); skills.value=s.items; mcps.value=m.items; invocations.value=i.items; } catch (cause) { error.value=cause instanceof Error?cause.message:"加载失败"; } }
async function run(key: string, action: () => Promise<void>) { error.value=""; busy.value=key; try { await action(); } catch (cause) { error.value=cause instanceof Error?cause.message:"操作失败"; } finally { busy.value=""; } }
async function upload(file: File) { await run("upload", async()=>{ const row=await apiRequest<Skill>("/api/business/skills/upload", { method:"POST", headers:{"Content-Type":file.type||"application/zip"}, body:file }); skills.value.push(row); }); }
async function mutate(skill: Skill, action: "publish"|"disable") { await run(`skill-${skill.id}`, async()=>{ const row=await apiRequest<Skill>(`/api/business/skills/${skill.id}/${action}`, {method:"POST"}); Object.assign(skill,row); }); }
async function authorize(skill: Skill) { const manager_user_id=managerIds.value[skill.id]?.trim(); if(!manager_user_id)return; await run(`auth-${skill.id}`, async()=>{ await apiRequest(`/api/business/skills/${skill.id}/authorizations`, {method:"POST",body:JSON.stringify({manager_user_id})}); managerIds.value[skill.id]=""; }); }
async function registerMcp() { await run("register-mcp", async()=>{ const row=await apiRequest<Mcp>("/api/business/mcp-servers", {method:"POST",body:JSON.stringify({name:mcpForm.value.name,command:mcpForm.value.command,args:mcpForm.value.args.split(/\s+/).filter(Boolean),env:{}})}); mcps.value.push(row); mcpForm.value={name:"",command:"",args:""}; }); }
async function testMcp(server: Mcp) { await run(`mcp-${server.id}`, async()=>{ const result=await apiRequest<{healthy:boolean;tools?:McpTool[]}>(`/api/business/mcp-servers/${server.id}/test`, {method:"POST"}); server.status=result.healthy?"healthy":"unavailable"; server.tools=result.tools??[]; }); }
async function stopMcp(server: Mcp) { await run(`mcp-stop-${server.id}`, async()=>{ await apiRequest(`/api/business/mcp-servers/${server.id}/stop`, {method:"POST"}); server.status="stopped"; server.tools=[]; }); }
async function authorizeMcp(server: Mcp) { const manager_user_id=mcpManagerIds.value[server.id]?.trim(); if(!manager_user_id)return; await run(`mcp-auth-${server.id}`, async()=>{ await apiRequest(`/api/business/mcp-servers/${server.id}/authorizations`, {method:"POST",body:JSON.stringify({manager_user_id})}); mcpManagerIds.value[server.id]=""; }); }
onMounted(load);
</script>
<template>
  <main class="admin-shell"><aside class="admin-nav"><p class="eyebrow green">BUSINESS CONTROL</p><h2>业务治理台</h2><nav><button :class="{active:active==='skills'}" @click="active='skills'"><span>◇</span>Skill 管理</button><button :class="{active:active==='mcp'}" @click="active='mcp'"><span>⌘</span>MCP Server</button><button :class="{active:active==='invocations'}" @click="active='invocations'"><span>↗</span>调用记录</button></nav><div class="scope-card"><strong>全局治理权限</strong><p>配置能力与授权范围，不参与客户经理真实业务。</p></div></aside>
    <section class="admin-content"><header class="admin-header"><div><p class="eyebrow green">{{active==='skills'?'CAPABILITY GOVERNANCE':active==='mcp'?'TOOL CONNECTIVITY':'OPERATION METADATA'}}</p><h1>{{active==='skills'?'Skill 能力管理':active==='mcp'?'MCP Server 管理':'Skill 调用记录'}}</h1><p>{{active==='skills'?'从本机安装、验证、发布并授权给指定客户经理。':active==='mcp'?'登记本地进程型 MCP Server，并执行连通性测试。':'查看调用状态和归属元数据，不展示业务正文。'}}</p></div><span class="status-badge">Phase 1</span></header><p v-if="error" class="alert error">{{error}}</p>
      <template v-if="active==='skills'"><SkillUpload :disabled="Boolean(busy)" @upload="upload"/><section class="data-card"><div class="card-title"><h2>已安装 Skill</h2><span>{{skills.length}} 项</span></div><div class="table-wrap"><table><thead><tr><th>Skill</th><th>类型 / 版本</th><th>状态</th><th>经理授权</th><th>操作</th></tr></thead><tbody><tr v-for="skill in skills" :key="skill.id"><td><strong>{{skill.name}}</strong><small>{{skill.description||'本地能力包'}}</small></td><td>{{skill.type}} · {{skill.version}}</td><td><span class="tag" :class="skill.status">{{skill.status==='published'?'已发布':skill.status==='disabled'?'已停用':'草稿'}}</span></td><td><div class="inline-form"><input v-model="managerIds[skill.id]" :aria-label="`授权 ${skill.name} 给经理`" placeholder="经理用户 ID" :disabled="Boolean(busy)"/><button class="button secondary compact" :disabled="Boolean(busy)" @click="authorize(skill)">授权</button></div></td><td><button v-if="skill.status!=='published'" class="button primary compact" :disabled="Boolean(busy)" @click="mutate(skill,'publish')">发布</button><button v-else class="button ghost compact" :disabled="Boolean(busy)" @click="mutate(skill,'disable')">停用</button></td></tr><tr v-if="!skills.length"><td colspan="5" class="table-empty">尚未安装 Skill，可从上方选择本地 ZIP。</td></tr></tbody></table></div></section></template>
      <template v-else-if="active==='mcp'"><section class="form-card"><h2>登记本地 MCP Server</h2><div class="form-grid three"><label>显示名称<input v-model="mcpForm.name" placeholder="mock-reception"/></label><label>命令<input v-model="mcpForm.command" placeholder="python"/></label><label>参数<input v-model="mcpForm.args" placeholder="scripts/mock_mcp.py"/></label></div><button class="button primary" :disabled="Boolean(busy)" @click="registerMcp">登记 Server</button></section><section class="data-card"><div class="card-title"><h2>Server 列表</h2><span>{{mcps.length}} 项</span></div><div v-for="server in mcps" :key="server.id" class="server-row"><span class="server-icon">⌘</span><div><strong>{{server.name}}</strong><small>{{server.transport}} · {{server.status}}</small></div><div class="inline-form"><input v-model="mcpManagerIds[server.id]" :aria-label="`授权 ${server.name} MCP 给经理`" placeholder="经理用户 ID" :disabled="Boolean(busy)"/><button class="button secondary compact" :disabled="Boolean(busy)" @click="authorizeMcp(server)">授权</button></div><button class="button secondary compact" :disabled="Boolean(busy)" @click="testMcp(server)">测试连接</button><button class="button ghost compact" :disabled="Boolean(busy) || server.status === 'stopped'" @click="stopMcp(server)">停止</button></div><p v-if="!mcps.length" class="table-empty">暂无 MCP Server</p></section></template>
      <template v-else><section class="data-card"><div class="card-title"><h2>最近调用</h2><span>仅元数据</span></div><div class="table-wrap"><table><thead><tr><th>Skill ID</th><th>客户经理</th><th>会话</th><th>状态</th><th>时间</th></tr></thead><tbody><tr v-for="row in invocations" :key="row.id"><td>{{row.skill_id}}</td><td>{{row.owner_user_id}}</td><td>{{row.session_id}}</td><td><span class="tag published">{{row.status}}</span></td><td>{{row.created_at||'—'}}</td></tr><tr v-if="!invocations.length"><td colspan="5" class="table-empty">暂无调用记录</td></tr></tbody></table></div></section></template>
    </section>
    <div class="operation-feedback" aria-live="polite">
      <p v-if="busy" class="status-badge">处理中…</p>
      <template v-for="skill in skills" :key="`warnings-${skill.id}`"><p v-for="warning in skill.validation_warnings" :key="warning" class="alert warning">{{ warning }}</p></template>
      <template v-for="server in mcps" :key="`tools-${server.id}`"><span v-for="tool in server.tools" :key="tool.name" class="tag published"><strong>{{ tool.name }}</strong><small v-if="tool.description">{{ tool.description }}</small></span></template>
    </div>
  </main>
</template>
