<script setup lang="ts">
import { onMounted, ref } from "vue";
import { apiRequest } from "@/api/client";
import { roleName, type Role } from "@/stores/auth";
type User={id:string;username:string;role:Role;is_active:boolean;created_at?:string};
type ModelStatus={configured:boolean;model:string;base_url:string;connectivity:string};
type Audit={id:string;actor_user_id:string;action:string;resource_type:string;result:string;request_id?:string;created_at?:string};
const users=ref<User[]>([]);const audits=ref<Audit[]>([]);const model=ref<ModelStatus>();const active=ref<"users"|"model"|"audit">("users");const error=ref("");const busy=ref("");
const form=ref<{username:string;password:string;role:Role}>({username:"",password:"",role:"manager"});
async function load(){try{const[u,m,a]=await Promise.all([apiRequest<{items:User[]}>("/api/system/users"),apiRequest<ModelStatus>("/api/system/model/status"),apiRequest<{items:Audit[]}>("/api/system/audit-logs")]);users.value=u.items;model.value=m;audits.value=a.items;}catch(cause){error.value=cause instanceof Error?cause.message:"加载失败";}}
async function run(key:string,action:()=>Promise<void>){error.value="";busy.value=key;try{await action();}catch(cause){error.value=cause instanceof Error?cause.message:"操作失败";}finally{busy.value="";}}
async function createUser(){await run("create",async()=>{const row=await apiRequest<User>("/api/system/users",{method:"POST",body:JSON.stringify({...form.value,is_active:true})});users.value.push(row);form.value={username:"",password:"",role:"manager"};});}
async function toggle(user:User){await run(`toggle-${user.id}`,async()=>{const row=await apiRequest<User>(`/api/system/users/${user.id}`,{method:"PATCH",body:JSON.stringify({is_active:!user.is_active})});Object.assign(user,row);});}
async function changeRole(user:User,event:Event){const role=(event.target as HTMLSelectElement).value as Role;await run(`role-${user.id}`,async()=>{const row=await apiRequest<User>(`/api/system/users/${user.id}`,{method:"PATCH",body:JSON.stringify({role})});Object.assign(user,row);});}
onMounted(load);
</script>
<template><main class="admin-shell"><aside class="admin-nav"><p class="eyebrow green">SYSTEM CONTROL</p><h2>系统治理台</h2><nav><button :class="{active:active==='users'}" @click="active='users'"><span>◎</span>用户与角色</button><button :class="{active:active==='model'}" @click="active='model'"><span>◫</span>模型状态</button><button :class="{active:active==='audit'}" @click="active='audit'"><span>≡</span>审计日志</button></nav><div class="scope-card"><strong>系统管理权限</strong><p>维护账号、角色和平台状态，不进入经理业务空间。</p></div></aside><section class="admin-content"><header class="admin-header"><div><p class="eyebrow green">PLATFORM GOVERNANCE</p><h1>{{active==='users'?'用户与角色':active==='model'?'模型运行状态':'平台审计日志'}}</h1><p>{{active==='users'?'创建账号、调整角色并控制启停状态。':active==='model'?'仅展示安全配置摘要，不暴露任何凭据。':'按时间查看平台治理和业务调用事件。'}}</p></div><span class="status-badge">Bank Demo</span></header><p v-if="error" class="alert error">{{error}}</p>
<template v-if="active==='users'"><section class="form-card"><h2>创建平台用户</h2><div class="form-grid"><label>新用户名<input v-model="form.username" aria-label="新用户名" placeholder="manager0003"/></label><label>初始密码<input v-model="form.password" aria-label="初始密码" type="password" placeholder="至少 8 位"/></label><label>角色<select v-model="form.role"><option value="manager">客户经理</option><option value="business_admin">业务管理员</option><option value="system_admin">系统管理员</option></select></label></div><button class="button primary" @click="createUser">创建用户</button></section><section class="data-card"><div class="card-title"><h2>平台用户</h2><span>{{users.length}} 人</span></div><div class="table-wrap"><table><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td><strong>{{user.username}}</strong><small>{{user.id}}</small></td><td><select :value="user.role" :aria-label="`调整 ${user.username} 角色`" @change="changeRole(user,$event)"><option value="manager">客户经理</option><option value="business_admin">业务管理员</option><option value="system_admin">系统管理员</option></select></td><td><span class="tag" :class="user.is_active?'published':'disabled'">{{user.is_active?'已启用':'已停用'}}</span></td><td><button class="button ghost compact" @click="toggle(user)">{{user.is_active?'停用':'启用'}}</button></td></tr><tr v-if="!users.length"><td colspan="4" class="table-empty">暂无用户</td></tr></tbody></table></div></section></template>
<template v-else-if="active==='model'"><section class="model-card" v-if="model"><div class="model-orb">AI</div><div><p class="eyebrow green">MODEL PROVIDER</p><h2>{{model.model}}</h2><p>{{model.base_url}}</p></div><span class="tag" :class="model.configured?'published':'disabled'">{{model.configured?'已配置':'未配置'}}</span></section><div class="metric-grid"><article><span>配置状态</span><strong>{{model?.configured?'可用':'待配置'}}</strong><small>凭据只在后端构造模型时使用</small></article><article><span>连通性</span><strong>{{model?.connectivity||'—'}}</strong><small>Phase 1 不在页面执行真实探测</small></article><article><span>安全边界</span><strong>凭据不可见</strong><small>响应不返回敏感字段</small></article></div></template>
<template v-else><section class="data-card"><div class="card-title"><h2>最新事件</h2><span>{{audits.length}} 条</span></div><div class="table-wrap"><table><thead><tr><th>操作</th><th>资源</th><th>结果</th><th>请求 ID</th><th>时间</th></tr></thead><tbody><tr v-for="row in audits" :key="row.id"><td><strong>{{row.action}}</strong><small>{{row.actor_user_id}}</small></td><td>{{row.resource_type}}</td><td><span class="tag" :class="row.result==='success'?'published':'disabled'">{{row.result}}</span></td><td>{{row.request_id||'—'}}</td><td>{{row.created_at||'—'}}</td></tr><tr v-if="!audits.length"><td colspan="5" class="table-empty">暂无审计事件</td></tr></tbody></table></div></section></template>
</section><p v-if="busy" class="operation-busy status-badge" aria-live="polite">处理中…</p></main></template>
